//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int ID_Employee { get; set; }
        public string Name_of_employee { get; set; }
        public int ID_JobTitle { get; set; }
    
        public virtual Job_titles Job_titles { get; set; }
    }
}
